# Generated by Django 5.0.11 on 2025-02-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('modulo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado da questão')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='perguntas/', verbose_name='Imagem da questão')),
                ('nivel', models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], max_length=1, verbose_name='Nível da questão')),
                ('alternativa_a', models.CharField(max_length=200, verbose_name='Alternativa A')),
                ('alternativa_b', models.CharField(max_length=200, verbose_name='Alternativa B')),
                ('alternativa_c', models.CharField(max_length=200, verbose_name='Alternativa C')),
                ('alternativa_d', models.CharField(max_length=200, verbose_name='Alternativa D')),
                ('alternativa_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Alternativa Correta')),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='perguntas.conteudo')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
    ]
