# Generated by Django 5.0.11 on 2025-01-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='data_atualizacao',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='data_criacao',
        ),
    ]
